"""Remove company relationship from PeopleData and CompanyData

Revision ID: 048ff56dac25
Revises: 5b4f9cf3e86b
Create Date: 2025-08-11 18:55:17.663262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '048ff56dac25'
down_revision: Union[str, Sequence[str], None] = '5b4f9cf3e86b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
