"""add diversified growth, alternatives, and insurance contracts columns

Revision ID: 1f1fdd325b3b
Revises: d3e14e66c8b5
Create Date: 2025-09-18 12:08:52.304878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f1fdd325b3b'
down_revision: Union[str, Sequence[str], None] = 'd3e14e66c8b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('key_financial_data', sa.Column('assets_diversified_growth', sa.Numeric(precision=20, scale=2), nullable=True))
    op.add_column('key_financial_data', sa.Column('assets_alternatives', sa.Numeric(precision=20, scale=2), nullable=True))
    op.add_column('key_financial_data', sa.Column('assets_insurance_contracts', sa.Numeric(precision=20, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('key_financial_data', 'assets_insurance_contracts')
    op.drop_column('key_financial_data', 'assets_alternatives')
    op.drop_column('key_financial_data', 'assets_diversified_growth')
    # ### end Alembic commands ###
