"""Remove registration_number from CompanyData

Revision ID: 31df4e72c110
Revises: 3dbdd4e0aaf1
Create Date: 2025-07-22 12:24:16.274556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '31df4e72c110'
down_revision: Union[str, Sequence[str], None] = '3dbdd4e0aaf1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company_data', 'registration_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_data', sa.Column('registration_number', mysql.VARCHAR(length=100), nullable=True))
    # ### end Alembic commands ###
