"""create company_pdfs table

Revision ID: 32d1682894bb
Revises: b67528f5d977
Create Date: 2025-08-28 14:13:17.828682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32d1682894bb'
down_revision: Union[str, Sequence[str], None] = 'b67528f5d977'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_pdfs',
    sa.Column('company_registered_number', sa.String(length=50), nullable=False),
    sa.Column('pdf_links', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('company_registered_number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('company_pdfs')
    # ### end Alembic commands ###
