"""Add scheme type, last modified, people & summary links

Revision ID: 3dbdd4e0aaf1
Revises: 40a4adca0338
Create Date: 2025-07-18 14:12:53.704031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3dbdd4e0aaf1'
down_revision: Union[str, Sequence[str], None] = '40a4adca0338'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_data', sa.Column('type_of_scheme', sa.String(length=100), nullable=True))
    op.add_column('company_data', sa.Column('last_modified', sa.DateTime(), nullable=True))
    op.add_column('company_data', sa.Column('people_page_link', sa.String(length=255), nullable=True))
    op.add_column('company_data', sa.Column('summary_notes_link', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company_data', 'summary_notes_link')
    op.drop_column('company_data', 'people_page_link')
    op.drop_column('company_data', 'last_modified')
    op.drop_column('company_data', 'type_of_scheme')
    # ### end Alembic commands ###
