"""Remove unused fields from CompanyData

Revision ID: 40a4adca0338
Revises: d5592b5b904a
Create Date: 2025-07-18 14:10:49.273989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '40a4adca0338'
down_revision: Union[str, Sequence[str], None] = 'd5592b5b904a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('identifier'), table_name='company_data')
    op.drop_column('company_data', 'identifier')
    op.drop_column('company_data', 'director_info')
    op.drop_column('company_data', 'pension_summary')
    op.drop_column('company_data', 'selected')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_data', sa.Column('selected', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('company_data', sa.Column('pension_summary', mysql.TEXT(), nullable=True))
    op.add_column('company_data', sa.Column('director_info', mysql.TEXT(), nullable=True))
    op.add_column('company_data', sa.Column('identifier', mysql.VARCHAR(length=20), nullable=True))
    op.create_index(op.f('identifier'), 'company_data', ['identifier'], unique=True)
    # ### end Alembic commands ###
