"""Replace individual columns with JSON for financial groups

Revision ID: 420f80b80ba4
Revises: 6896e218bcea
Create Date: 2025-07-11 18:29:47.311655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '420f80b80ba4'
down_revision: Union[str, Sequence[str], None] = '6896e218bcea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('key_financial_data', sa.Column('turnover_data', sa.JSON(), nullable=True))
    op.add_column('key_financial_data', sa.Column('profit_data', sa.JSON(), nullable=True))
    op.add_column('key_financial_data', sa.Column('fair_value_assets', sa.JSON(), nullable=True))
    op.add_column('key_financial_data', sa.Column('surplus_data', sa.JSON(), nullable=True))
    op.drop_column('key_financial_data', 'profit_2019')
    op.drop_column('key_financial_data', 'fair_value_assets_prev_year_end')
    op.drop_column('key_financial_data', 'profit_latest_year')
    op.drop_column('key_financial_data', 'surplus_year_end')
    op.drop_column('key_financial_data', 'turnover_2019')
    op.drop_column('key_financial_data', 'surplus_2020')
    op.drop_column('key_financial_data', 'profit_previous_year')
    op.drop_column('key_financial_data', 'profit_2020')
    op.drop_column('key_financial_data', 'turnover_latest_year')
    op.drop_column('key_financial_data', 'turnover_previous_year')
    op.drop_column('key_financial_data', 'surplus_2019')
    op.drop_column('key_financial_data', 'fair_value_assets_2019')
    op.drop_column('key_financial_data', 'fair_value_assets_2020')
    op.drop_column('key_financial_data', 'turnover_2020')
    op.drop_column('key_financial_data', 'surplus_prev_year_end')
    op.drop_column('key_financial_data', 'fair_value_assets_year_end')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('key_financial_data', sa.Column('fair_value_assets_year_end', mysql.DECIMAL(precision=20, scale=2), nullable=True))
    op.add_column('key_financial_data', sa.Column('surplus_prev_year_end', mysql.DECIMAL(precision=20, scale=2), nullable=True))
    op.add_column('key_financial_data', sa.Column('turnover_2020', mysql.DECIMAL(precision=20, scale=4), nullable=True))
    op.add_column('key_financial_data', sa.Column('fair_value_assets_2020', mysql.DECIMAL(precision=20, scale=2), nullable=True))
    op.add_column('key_financial_data', sa.Column('fair_value_assets_2019', mysql.DECIMAL(precision=20, scale=2), nullable=True))
    op.add_column('key_financial_data', sa.Column('surplus_2019', mysql.DECIMAL(precision=20, scale=2), nullable=True))
    op.add_column('key_financial_data', sa.Column('turnover_previous_year', mysql.DECIMAL(precision=20, scale=4), nullable=True))
    op.add_column('key_financial_data', sa.Column('turnover_latest_year', mysql.DECIMAL(precision=20, scale=4), nullable=True))
    op.add_column('key_financial_data', sa.Column('profit_2020', mysql.DECIMAL(precision=20, scale=4), nullable=True))
    op.add_column('key_financial_data', sa.Column('profit_previous_year', mysql.DECIMAL(precision=20, scale=4), nullable=True))
    op.add_column('key_financial_data', sa.Column('surplus_2020', mysql.DECIMAL(precision=20, scale=2), nullable=True))
    op.add_column('key_financial_data', sa.Column('turnover_2019', mysql.DECIMAL(precision=20, scale=4), nullable=True))
    op.add_column('key_financial_data', sa.Column('surplus_year_end', mysql.DECIMAL(precision=20, scale=2), nullable=True))
    op.add_column('key_financial_data', sa.Column('profit_latest_year', mysql.DECIMAL(precision=20, scale=4), nullable=True))
    op.add_column('key_financial_data', sa.Column('fair_value_assets_prev_year_end', mysql.DECIMAL(precision=20, scale=2), nullable=True))
    op.add_column('key_financial_data', sa.Column('profit_2019', mysql.DECIMAL(precision=20, scale=4), nullable=True))
    op.drop_column('key_financial_data', 'surplus_data')
    op.drop_column('key_financial_data', 'fair_value_assets')
    op.drop_column('key_financial_data', 'profit_data')
    op.drop_column('key_financial_data', 'turnover_data')
    # ### end Alembic commands ###
