"""Remove company_id from PeopleData

Revision ID: 5b4f9cf3e86b
Revises: 687d954f0611
Create Date: 2025-08-11 18:54:29.731007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5b4f9cf3e86b'
down_revision: Union[str, Sequence[str], None] = '687d954f0611'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('people_data_ibfk_1'), 'people_data', type_='foreignkey')
    op.drop_column('people_data', 'company_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('people_data', sa.Column('company_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('people_data_ibfk_1'), 'people_data', 'company_data', ['company_id'], ['id'])
    # ### end Alembic commands ###
