"""Make key_financial_data_id unique in company_data

Revision ID: 6413264860bc
Revises: 81e5637c755d
Create Date: 2025-10-07 12:53:31.626767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6413264860bc'
down_revision: Union[str, Sequence[str], None] = '81e5637c755d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # First, remove any existing duplicates (keep the first occurrence of each key_financial_data_id)
    op.execute("""
        DELETE cd1 FROM company_data cd1
        INNER JOIN company_data cd2 
        WHERE cd1.id > cd2.id 
        AND cd1.key_financial_data_id = cd2.key_financial_data_id
        AND cd1.key_financial_data_id IS NOT NULL
    """)
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_company_data_key_financial_data_id', 'company_data', ['key_financial_data_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_company_data_key_financial_data_id', 'company_data', type_='unique')
    # ### end Alembic commands ###
