"""Add company_registered_number to PeopleData

Revision ID: 687d954f0611
Revises: 550c6daba6d8
Create Date: 2025-08-11 18:27:32.489645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '687d954f0611'
down_revision: Union[str, Sequence[str], None] = '550c6daba6d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('people_data', sa.Column('company_registered_number', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('people_data', 'company_registered_number')
    # ### end Alembic commands ###
