"""Add status field to company_data

Revision ID: 6896e218bcea
Revises: c095796ea2b9
Create Date: 2025-07-10 14:37:45.608958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6896e218bcea'
down_revision: Union[str, Sequence[str], None] = 'c095796ea2b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_data', sa.Column('status', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company_data', 'status')
    # ### end Alembic commands ###
