"""Remove summary_notes_link column from company_data

Revision ID: 6c791bbf6bfa
Revises: 048ff56dac25
Create Date: 2025-08-13 15:21:52.319944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6c791bbf6bfa'
down_revision: Union[str, Sequence[str], None] = '048ff56dac25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company_data', 'summary_notes_link')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_data', sa.Column('summary_notes_link', mysql.VARCHAR(length=255), nullable=True))
    # ### end Alembic commands ###
