"""updated key financial data

Revision ID: 81e5637c755d
Revises: 939ccc25266c
Create Date: 2025-09-25 11:53:58.098341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81e5637c755d'
down_revision: Union[str, Sequence[str], None] = '939ccc25266c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('key_financial_data', sa.Column('current_company_name', sa.String(length=255), nullable=True))
    op.add_column('key_financial_data', sa.Column('sic1', sa.Integer(), nullable=True))
    op.add_column('key_financial_data', sa.Column('sic2', sa.Integer(), nullable=True))
    op.add_column('key_financial_data', sa.Column('location', sa.String(length=255), nullable=True))
    op.add_column('key_financial_data', sa.Column('nature_of_business', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('key_financial_data', 'nature_of_business')
    op.drop_column('key_financial_data', 'location')
    op.drop_column('key_financial_data', 'sic2')
    op.drop_column('key_financial_data', 'sic1')
    op.drop_column('key_financial_data', 'current_company_name')
    # ### end Alembic commands ###
