"""create company charges

Revision ID: 8d9aeca9737a
Revises: 32d1682894bb
Create Date: 2025-09-12 13:41:55.102661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d9aeca9737a'
down_revision: Union[str, Sequence[str], None] = '32d1682894bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_charges',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_registered_number', sa.String(length=50), nullable=False),
    sa.Column('total_charges', sa.Integer(), nullable=False),
    sa.Column('charges', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_registered_number')
    )
    op.create_index(op.f('ix_company_charges_id'), 'company_charges', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_company_charges_id'), table_name='company_charges')
    op.drop_table('company_charges')
    # ### end Alembic commands ###
