"""create key_financial_data table

Revision ID: 944424ec6daa
Revises: 16ef42737feb
Create Date: 2025-07-04 15:32:52.455708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '944424ec6daa'
down_revision: Union[str, Sequence[str], None] = '16ef42737feb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('key_financial_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('company_status', sa.String(length=50), nullable=True),
    sa.Column('company_registered_number', sa.Integer(), nullable=True),
    sa.Column('incorporation_date', sa.Date(), nullable=True),
    sa.Column('latest_accounts_date', sa.Date(), nullable=True),
    sa.Column('turnover_latest_year', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('turnover_previous_year', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('turnover_2020', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('turnover_2019', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('profit_latest_year', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('profit_previous_year', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('profit_2020', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('profit_2019', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('parent_company', sa.String(length=255), nullable=True),
    sa.Column('nationality_of_parent', sa.String(length=100), nullable=True),
    sa.Column('auditor_name_latest', sa.String(length=255), nullable=True),
    sa.Column('auditor_firm_latest', sa.String(length=255), nullable=True),
    sa.Column('number_of_uk_defined_benefit_arrangements', sa.Integer(), nullable=True),
    sa.Column('Name_of_Defined_Benefit_Arrangement_1', sa.String(length=255), nullable=True),
    sa.Column('scheme_actuary_1', sa.String(length=255), nullable=True),
    sa.Column('scheme_actuary_firm_1', sa.String(length=255), nullable=True),
    sa.Column('Status_of_Defined_Benefit_Arrangement_1', sa.String(length=100), nullable=True),
    sa.Column('Name_of_Defined_Benefit_Arrangement_2', sa.String(length=255), nullable=True),
    sa.Column('scheme_actuary_2', sa.String(length=255), nullable=True),
    sa.Column('scheme_actuary_firm_2', sa.String(length=255), nullable=True),
    sa.Column('Status_of_Defined_Benefit_Arrangement_2', sa.String(length=100), nullable=True),
    sa.Column('Name_of_Defined_Benefit_Arrangement_3', sa.String(length=255), nullable=True),
    sa.Column('scheme_actuary_3', sa.String(length=255), nullable=True),
    sa.Column('scheme_actuary_firm_3', sa.String(length=255), nullable=True),
    sa.Column('Status_of_Defined_Benefit_Arrangement_3', sa.String(length=100), nullable=True),
    sa.Column('fair_value_assets_year_end', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('fair_value_assets_prev_year_end', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('fair_value_assets_2020', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('fair_value_assets_2019', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('surplus_year_end', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('surplus_prev_year_end', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('surplus_2020', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('surplus_2019', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('employer_contrib_latest_year', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('employer_contrib_previous_year', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('benefits_paid', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('expenses_paid_latest_year', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('expenses_paid_previous_year', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('defined_contrib_paid', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('assets_equities', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('assets_bonds', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('assets_real_estate', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('assets_ldi', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('assets_cash', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('assets_other', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_registered_number')
    )
    op.create_index(op.f('ix_key_financial_data_id'), 'key_financial_data', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_key_financial_data_id'), table_name='key_financial_data')
    op.drop_table('key_financial_data')
    # ### end Alembic commands ###
