"""Remove downloaded_pdfs from company_data

Revision ID: a7b1bb8ade88
Revises: e555c409fa7b
Create Date: 2025-08-11 14:18:04.461658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a7b1bb8ade88'
down_revision: Union[str, Sequence[str], None] = 'e555c409fa7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company_data', 'downloaded_pdfs')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_data', sa.Column('downloaded_pdfs', mysql.TEXT(), nullable=True))
    # ### end Alembic commands ###
