"""create_summary_notes_table

Revision ID: b67528f5d977
Revises: 6c791bbf6bfa
Create Date: 2025-08-13 15:39:23.924501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b67528f5d977'
down_revision: Union[str, Sequence[str], None] = '6c791bbf6bfa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('summary_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_registered_number', sa.String(length=20), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_summary_notes_company_registered_number'), 'summary_notes', ['company_registered_number'], unique=False)
    op.create_index(op.f('ix_summary_notes_id'), 'summary_notes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_summary_notes_id'), table_name='summary_notes')
    op.drop_index(op.f('ix_summary_notes_company_registered_number'), table_name='summary_notes')
    op.drop_table('summary_notes')
    # ### end Alembic commands ###
