"""Change numeric fields to float in key_financial_data

Revision ID: beb2294e4310
Revises: 6413264860bc
Create Date: 2025-10-14 14:21:15.453837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'beb2294e4310'
down_revision: Union[str, Sequence[str], None] = '6413264860bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('key_financial_data', 'employer_contrib_latest_year',
               existing_type=mysql.DECIMAL(precision=20, scale=1),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('key_financial_data', 'employer_contrib_previous_year',
               existing_type=mysql.DECIMAL(precision=20, scale=1),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('key_financial_data', 'benefits_paid',
               existing_type=mysql.DECIMAL(precision=20, scale=1),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('key_financial_data', 'expenses_paid_latest_year',
               existing_type=mysql.DECIMAL(precision=20, scale=1),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('key_financial_data', 'expenses_paid_previous_year',
               existing_type=mysql.DECIMAL(precision=20, scale=1),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('key_financial_data', 'defined_contrib_paid',
               existing_type=mysql.DECIMAL(precision=20, scale=1),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('key_financial_data', 'assets_equities',
               existing_type=mysql.DECIMAL(precision=20, scale=1),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('key_financial_data', 'assets_bonds',
               existing_type=mysql.DECIMAL(precision=20, scale=1),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('key_financial_data', 'assets_real_estate',
               existing_type=mysql.DECIMAL(precision=20, scale=1),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('key_financial_data', 'assets_ldi',
               existing_type=mysql.DECIMAL(precision=20, scale=1),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('key_financial_data', 'assets_cash',
               existing_type=mysql.DECIMAL(precision=20, scale=1),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('key_financial_data', 'assets_other',
               existing_type=mysql.DECIMAL(precision=20, scale=1),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('key_financial_data', 'assets_diversified_growth',
               existing_type=mysql.DECIMAL(precision=20, scale=1),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('key_financial_data', 'assets_alternatives',
               existing_type=mysql.DECIMAL(precision=20, scale=1),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('key_financial_data', 'assets_insurance_contracts',
               existing_type=mysql.DECIMAL(precision=20, scale=1),
               type_=sa.Float(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('key_financial_data', 'assets_insurance_contracts',
               existing_type=sa.Float(),
               type_=mysql.DECIMAL(precision=20, scale=1),
               existing_nullable=True)
    op.alter_column('key_financial_data', 'assets_alternatives',
               existing_type=sa.Float(),
               type_=mysql.DECIMAL(precision=20, scale=1),
               existing_nullable=True)
    op.alter_column('key_financial_data', 'assets_diversified_growth',
               existing_type=sa.Float(),
               type_=mysql.DECIMAL(precision=20, scale=1),
               existing_nullable=True)
    op.alter_column('key_financial_data', 'assets_other',
               existing_type=sa.Float(),
               type_=mysql.DECIMAL(precision=20, scale=1),
               existing_nullable=True)
    op.alter_column('key_financial_data', 'assets_cash',
               existing_type=sa.Float(),
               type_=mysql.DECIMAL(precision=20, scale=1),
               existing_nullable=True)
    op.alter_column('key_financial_data', 'assets_ldi',
               existing_type=sa.Float(),
               type_=mysql.DECIMAL(precision=20, scale=1),
               existing_nullable=True)
    op.alter_column('key_financial_data', 'assets_real_estate',
               existing_type=sa.Float(),
               type_=mysql.DECIMAL(precision=20, scale=1),
               existing_nullable=True)
    op.alter_column('key_financial_data', 'assets_bonds',
               existing_type=sa.Float(),
               type_=mysql.DECIMAL(precision=20, scale=1),
               existing_nullable=True)
    op.alter_column('key_financial_data', 'assets_equities',
               existing_type=sa.Float(),
               type_=mysql.DECIMAL(precision=20, scale=1),
               existing_nullable=True)
    op.alter_column('key_financial_data', 'defined_contrib_paid',
               existing_type=sa.Float(),
               type_=mysql.DECIMAL(precision=20, scale=1),
               existing_nullable=True)
    op.alter_column('key_financial_data', 'expenses_paid_previous_year',
               existing_type=sa.Float(),
               type_=mysql.DECIMAL(precision=20, scale=1),
               existing_nullable=True)
    op.alter_column('key_financial_data', 'expenses_paid_latest_year',
               existing_type=sa.Float(),
               type_=mysql.DECIMAL(precision=20, scale=1),
               existing_nullable=True)
    op.alter_column('key_financial_data', 'benefits_paid',
               existing_type=sa.Float(),
               type_=mysql.DECIMAL(precision=20, scale=1),
               existing_nullable=True)
    op.alter_column('key_financial_data', 'employer_contrib_previous_year',
               existing_type=sa.Float(),
               type_=mysql.DECIMAL(precision=20, scale=1),
               existing_nullable=True)
    op.alter_column('key_financial_data', 'employer_contrib_latest_year',
               existing_type=sa.Float(),
               type_=mysql.DECIMAL(precision=20, scale=1),
               existing_nullable=True)
    # ### end Alembic commands ###
