"""Add foreign key from company_data to key_financial_data

Revision ID: c095796ea2b9
Revises: 33994fb18dcf
Create Date: 2025-07-07 18:22:12.369057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c095796ea2b9'
down_revision: Union[str, Sequence[str], None] = '33994fb18dcf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_data', sa.Column('key_financial_data_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'company_data', 'key_financial_data', ['key_financial_data_id'], ['id'])
    op.drop_column('company_data', 'key_financial_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_data', sa.Column('key_financial_data', mysql.TEXT(), nullable=True))
    op.drop_constraint(None, 'company_data', type_='foreignkey')
    op.drop_column('company_data', 'key_financial_data_id')
    # ### end Alembic commands ###
