"""update unique constraint to people_data

Revision ID: d3e14e66c8b5
Revises: 8d9aeca9737a
Create Date: 2025-09-12 13:47:52.911999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3e14e66c8b5'
down_revision: Union[str, Sequence[str], None] = '8d9aeca9737a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_people_unique_combination', 'people_data', ['company_registered_number', 'role', 'name', 'appointment_date', 'date_of_birth'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_people_unique_combination', 'people_data', type_='unique')
    # ### end Alembic commands ###
