"""Update company_registered_number field

Revision ID: dbcc465c9ebe
Revises: b619c1eb5284
Create Date: 2025-07-22 12:38:31.096455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'dbcc465c9ebe'
down_revision: Union[str, Sequence[str], None] = '31df4e72c110'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('key_financial_data', 'company_registered_number',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.drop_index(op.f('company_registered_number'), table_name='key_financial_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('company_registered_number'), 'key_financial_data', ['company_registered_number'], unique=True)
    op.alter_column('key_financial_data', 'company_registered_number',
               existing_type=sa.String(length=50),
               type_=mysql.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
