"""Change incorporation_date and latest_accounts_date from Date to String

Revision ID: e555c409fa7b
Revises: 0afd673c4be7
Create Date: 2025-08-08 13:57:44.948185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e555c409fa7b'
down_revision: Union[str, Sequence[str], None] = '0afd673c4be7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('key_financial_data', 'incorporation_date',
               existing_type=sa.DATE(),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('key_financial_data', 'latest_accounts_date',
               existing_type=sa.DATE(),
               type_=sa.String(length=50),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('key_financial_data', 'latest_accounts_date',
               existing_type=sa.String(length=50),
               type_=sa.DATE(),
               existing_nullable=True)
    op.alter_column('key_financial_data', 'incorporation_date',
               existing_type=sa.String(length=50),
               type_=sa.DATE(),
               existing_nullable=True)
    # ### end Alembic commands ###
