"""Create company_data table

Revision ID: eef44e68ef63
Revises: 7a1c8c8dc3da
Create Date: 2025-07-02 15:59:57.309818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eef44e68ef63'
down_revision: Union[str, Sequence[str], None] = '7a1c8c8dc3da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('selected', sa.Boolean(), nullable=True),
    sa.Column('identifier', sa.String(length=20), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('key_financial_data', sa.Text(), nullable=True),
    sa.Column('downloaded_pdfs', sa.Text(), nullable=True),
    sa.Column('pension_summary', sa.Text(), nullable=True),
    sa.Column('director_info', sa.Text(), nullable=True),
    sa.Column('approval_stage', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identifier')
    )
    op.create_index(op.f('ix_company_data_id'), 'company_data', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_company_data_id'), table_name='company_data')
    op.drop_table('company_data')
    # ### end Alembic commands ###
