"""add unique constraint to PeopleData

Revision ID: fb4f3b327fad
Revises: 81e77c10e34f
Create Date: 2025-09-03 11:50:35.499898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb4f3b327fad'
down_revision: Union[str, Sequence[str], None] = '81e77c10e34f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('people_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=255), nullable=True),
    sa.Column('appointment_date', sa.String(length=50), nullable=True),
    sa.Column('date_of_birth', sa.String(length=50), nullable=True),
    sa.Column('company_registered_number', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_registered_number', 'role', 'name', 'appointment_date', 'date_of_birth', name='uq_people_unique_combination')
    )
    op.create_index(op.f('ix_people_data_id'), 'people_data', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_people_data_id'), table_name='people_data')
    op.drop_table('people_data')
    # ### end Alembic commands ###
